module.exports = [
  {
    files: ["public/assets/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "script",
      globals: {
        AbortController: "readonly",
        Array: "readonly",
        Boolean: "readonly",
        CustomEvent: "readonly",
        Date: "readonly",
        Element: "readonly",
        Error: "readonly",
        Event: "readonly",
        FormData: "readonly",
        HTMLElement: "readonly",
        HTMLAnchorElement: "readonly",
        IntersectionObserver: "readonly",
        JSON: "readonly",
        MutationObserver: "readonly",
        Node: "readonly",
        Object: "readonly",
        Promise: "readonly",
        String: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        location: "readonly",
        console: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["error", { "args": "none", "ignoreRestSiblings": true }],
    },
  },
];
