name: Deploy website by SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Upload website to webserver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload website by SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './*'
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
          sftp_only: true
          port: ${{ secrets.SFTP_PORT }}