name: Deploy website by SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Upload website to webserver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload website by SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
with:
  server: ${{ secrets.FTP_SERVER }}
  username: ${{ secrets.FTP_USERNAME }}
  password: ${{ secrets.FTP_PASSWORD }}
  server-dir: ${{ secrets.FTP_SERVER_DIR }}
  local-dir: ./
  protocol: ftps-legacy
  port: 222